name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v6.16.0
      with:
        context: ./study-api
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/misis-sdm-server:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v6.16.0
      with:
        context: ./front
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/misis-sdm-front:latest
